- airbyte-integrations/connectors/source-amazon-seller-partner/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-amazon-seller-partner/integration_tests/sample_config.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_BRAND_ANALYTICS_ALTERNATE_PURCHASE_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_BRAND_ANALYTICS_ITEM_COMPARISON_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_INVENTORY_AGED_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_INVENTORY_PLANNING_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FLAT_FILE_OPEN_LISTINGS_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_LEDGER_DETAIL_VIEW_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_MERCHANT_LISTINGS_ALL_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_SALES_AND_TRAFFIC_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_SELLER_FEEDBACK_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_VENDOR_INVENTORY_HEALTH_AND_PLANNING_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_XML_BROWSE_TREE_DATA.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/Orders.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/VendorDirectFulfillmentShipping.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> CU-2p6wrdr_sources_Roy--

- airbyte-integrations/connectors/source-amazon-ads/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-amazon-ads/integration_tests/sample_config.json
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/common.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/profile.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/sponsored_brands.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/sponsored_display.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/schemas/sponsored_products.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/common.py
> CU-2j4nqwg_Amazon-Adssourcesource-name_Roy--

- airbyte-workers/src/main/java/io/airbyte/workers/general/DefaultReplicationWorker.java
> CU-2jvcnu4_Daspire_Roy--

- airbyte-webapp/src/config/FrequencyConfig.json
> CU-2r1a78d_airbyte_Roy--

- airbyte-webapp/.storybook/theme.tsx
- airbyte-webapp/package-lock.json
- airbyte-webapp/src/components/Markdown/index.stories.tsx
- airbyte-webapp/src/components/base/Tooltip/index.stories.tsx
- airbyte-webapp/src/config/casesConfig.json
- airbyte-webapp/src/config/links.ts
- airbyte-webapp/src/packages/cloud/views/auth/Auth.tsx
- airbyte-webapp/src/packages/cloud/views/auth/components/GitBlock/__snapshots__/GitBlock.test.tsx.snap
Change all the "airbyte.com" to "daspire.com"
> CU-3h20xhp_Change-all-the-airbytecom-to-daspirecom-in-the-source-code-of-airbyte-webapp_Muhammad-Akif

- airbyte-integrations/connectors/source-amazon-seller-partner/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-amazon-seller-partner/integration_tests/sample_config.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_SALES_AND_TRAFFIC_REPORT.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
> CU-3feb8a0_Business-reports_Roy--

- airbyte-api/src/main/openapi/config.yaml
- airbyte-server/src/main/java/io/airbyte/server/handlers/WorkspacesHandler.java
> CU-3640vdh_BE-allow-user-to-sign-in_Roy--

- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/components/SwitchButton.tsx
- airbyte-webapp/src/config/defaultConfig.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/apiOverride.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
- airbyte-webapp/src/pages/OnboardingPage/components/WelcomeStep.tsx
- airbyte-webapp/src/pages/routes.tsx
I am done with the following task 
1. Create Source (Choose Github)
2. Create Destination (Choose Local Json)
3. Create Connection
4. Render Image if "No Connections Made" or 
5. Render Connection List Table 
6. Toggle button on the table to mark connection active or inactive.
> CU-37bxh8m_FE-integration-with-BE-for-add-connection-functionalities_Muhammad-Akif

- airbyte-webapp/src/config/configProviders.ts
- airbyte-webapp/src/config/defaultConfig.ts
- airbyte-webapp/src/core/request/AirbyteRequestService.ts
- airbyte-webapp/src/core/request/apiOverride.ts
> CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif

- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
change source name to store name
> CU-3c6jz0w_Rename-Source-Name-to-Store-Name_Jerry-Lee---

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
fixed the issue that amazon ads and amazon seller partner don't show the store name field.
> CU-3dmfq0y_Issue-for-source-amazon-ads-and-source-amazon-seller-partner-dont-show-the-store-name-when-the-system-is-running_Jerry-Lee---

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
Issue: for source-amazon-ads and source-amazon-seller-partner, don't show the store name when the system is running
> CU-3dmfq0y_Issue-for-source-amazon-ads-and-source-amazon-seller-partner-dont-show-the-store-name-when-the-system-is-running_Abi---

- airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/JavaBaseConstants.java
- airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/destination/StandardNameTransformer.java
- airbyte-integrations/bases/base-normalization/normalization/transform_catalog/catalog_processor.py
- airbyte-integrations/connectors/destination-mysql/src/test/java/io/airbyte/integrations/destination/mysql/MySQLNameTransformerTest.java
changed _airbyte to _daspire and fixed the issue
> CU-3wmftg4_issue-could-not-get-the-documentation-of-amazon-ads-and-amazon-seller-partner_Jerry-Lee---

- airbyte-webapp/src/components/ArrayOfObjectsEditor/ArrayOfObjectsEditor.tsx
- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/JobItem/JobItem.tsx
- airbyte-webapp/src/config/configProviders.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/locales/en.json
> CU-37bxrt6_FE-billing--payment-UI_Muhammad-Akif

- airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
- airbyte-config/init/src/main/resources/seed/destination_specs.yaml
- airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json
change destination-snowflake to support Daspire
> CU-3xbcnkr_Show-un-hide-Snowflake-destination_Jerry-Lee---

- airbyte-webapp/README.md
- airbyte-webapp/src/views/Connector/ConnectorCard/ConnectorCard.tsx
> CU-3epqq8z_Hide-error-log-from-frontend_Anet-

- airbyte-oauth/src/main/java/io/airbyte/oauth/MoreOAuthParameters.java
去除oauth认证跟据workspaceId查询认证配置信息
> CU-3defpdd_BE-use-LWA-to-authorize-Amazon-AdsSP_Roy--

- airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
- airbyte-webapp/src/pages/PaymentErrorPage/index.tsx
- airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
- airbyte-webapp/src/pages/routePaths.tsx
- airbyte-webapp/src/pages/routes.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
> CU-37bxrtt_FE-integrate-with-BE-for-upgrade-plan-functionalities_Muhammad-Akif

- airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/PlanClause.tsx
resolved bugs of payment which are assigned till today.
> CU-864dj93xf_BugIf-the-plan-page-writes-false-it-should-not-be-displayed_Muhammad-Akif

- airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java
- airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java
- airbyte-workers/src/main/java/io/airbyte/workers/HttpUtil.java
- airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
添加connection job失败调用Daspire接口发送邮件
> CU-860patqtu_Notify-user-when-sync-fails_Roy--

- airbyte-webapp/README.md
- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/components/ConnectionSettingsCell.tsx
- airbyte-webapp/src/components/base/Switch/Switch.tsx
CU-35jyyam - Ability to configure an existing connection
> CU-35jyyam_Ability-to-configure-an-existing-connection_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/NotificationPage/NotificationPage.tsx
> CU-3f7yuy4_Show-notification-settings-from-Airbyte_Anet-

- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
change airbyte to daspire in the spec.
> CU-864dkg2f2_Change-airbyte-to-daspire-in-source-amazon-ads_Jerry-Lee---

- airbyte-webapp/README.md
- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Show source & destination pages
> CU-860p9wqzc_Source--destination-pages_Anet-

- airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
> CU-3bfmwqj_Restrictions-based-on-pricing-plan_Roy--

- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
message prompt after updating subscription is successfull.
> CU-864djve4k_BugClick-the-Get-Offer-button-on-the-Upgrade-and-Schedule-page-without-response_Muhammad-Akif

- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
The prompt that the trial period exceeds 14 days is wrong (resolved)
> CU-864dkgrfy_bugThe-prompt-that-the-trial-period-exceeds-14-days-is-wrong_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
- airbyte-webapp/src/components/EntityTable/components/ConnectionCopyCell.tsx
- airbyte-webapp/src/core/analytics/types.ts
- airbyte-webapp/src/core/domain/connector/DestinationService.ts
- airbyte-webapp/src/core/domain/connector/SourceService.ts
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/locales/en.json
Add copy function for ource/destination page
> CU-35y4khq_Ability-to-copy-a-sourcedestination-and-its-configurations_Anet-

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
- airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
> CU-35yd1y4_Ability-to-filter-connections-on-dashboard_Roy--

- airbyte-webapp/src/config/defaultConfig.ts
- airbyte-webapp/src/config/types.ts
- airbyte-webapp/src/core/ApiServices.tsx
- airbyte-webapp/src/core/AuthContext/AuthContext.tsx
- airbyte-webapp/src/hooks/services/UserDetail/UserDetailPoll.tsx
- airbyte-webapp/src/hooks/services/UserDetail/index.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/routes.tsx
> CU-860pdx7kn_Role-management_Muhammad-Akif

- airbyte-workers/src/main/java/io/airbyte/workers/normalization/NormalizationRunnerFactory.java
> CU-865bed37b__Roy--

- airbyte-webapp/src/core/request/apiOverride.ts
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
All invite users bugs resolved.
> CU-865bfgnbe_bugNo-prompt-when-inviting-an-existing-email-accountand-it-is-always-loading_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/config/links.ts
Change link in connection config(Learn more)
> CU-86698hy91_Change-link-in-connection-config_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/JobItem/JobItem.tsx
> CU-86698hxbe_Hide-sync-log_Anet-

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
> CU-860pe7vb3_New-source-Walmart_Roy--

- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
- airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
- airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
- airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
- airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
Followings bugs resolved:
1. Sign up page UI issue
2. Sign up page Google button shows sign in
3. Not able to sign up / sign in with Google
4. Switching roles on the user management page, there is no banner prompt
> CU-860pme70e_Bug-sign-up-page-UI-issue_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/config/links.ts
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/views/Connector/ServiceForm/components/WarningMessage.tsx
change wording in Alpha connectors
> CU-860pk0t80_FE-change-wording-in-Alpha-connectors_Anet-

- airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
Google authentication UI and functionality bugs resolved.
> CU-860pme6my_Bug-not-able-to-sign-up-sign-in-with-Google_Muhammad-Akif

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
> CU-865bn1qrj_change-Airbyte-to-Daspire-in-the-description-of-source-amazon-ads-configuration_Jerry-Lee---

- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-shopify/Dockerfile
- airbyte-integrations/connectors/source-shopify/source_shopify/spec.json
> CU-860pu0r0k_Release-Shopify-as-a-source_Roy--

- airbyte-webapp/src/config/defaultConfig.ts
- airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
In LWA(Login with Amazon) redirect URL has been resolved and getRefresh token api after calling getConsentURL also integrated.
> CU-3pqm6zx_Ability-to-use-auth-to-set-up-Amazon-Ads--SP_Muhammad-Akif

- airbyte-api/src/main/openapi/config.yaml
- airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
> CU-865bpydm0__Roy--

- airbyte-webapp/src/components/Pagination/Pagination.tsx
- airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Pagination, pagination in URL and filtration is complete.
> CU-37c0c41_FE-integrate-with-BE-for-filter-functionalities_Muhammad-Akif

- airbyte-webapp/src/components/PageTitle/PageTitle.tsx
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
1. Button in a wired place
2. Page should not scrollable
3. Upgrade plan banner is redesigned
> CU-8669e63p3_Button-in-a-wired-place_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Change sidebar settings style as same as other buttons
> CU-860pg5eke_Button-styles-on-click-should-be-the-same_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
User management page, small screen automatic adaptation problem
> CU-865bqcaw1_BugUser-management-page-small-screen-automatic-adaptation-problem_Anet-

- airbyte-webapp/src/App.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Sidebar double click issue resolved
> CU-865btacyp_BugDouble-click-the-dashboard-to-report-an-error_Muhammad-Akif

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-ebay/integration_tests/catalog.json
- airbyte-integrations/connectors/source-ebay/source_ebay/source.py
- airbyte-integrations/connectors/source-ebay/source_ebay/spec.yaml
- docs/setup-guide/destinations/mysql.md
- docs/setup-guide/sources/amazon-ads.md
- docs/setup-guide/sources/amazon-seller-partner.md
- docs/setup-guide/sources/mysql.md
- docs/setup-guide/sources/shopify.md
- docs/zh/setup-guide/destinations/bigquery.md
- docs/zh/setup-guide/destinations/mysql.md
- docs/zh/setup-guide/destinations/redshift.md
- docs/zh/setup-guide/destinations/snowflake.md
- docs/zh/setup-guide/sources/amazon-ads.md
- docs/zh/setup-guide/sources/amazon-seller-partner.md
- docs/zh/setup-guide/sources/bigcommerce.md
- docs/zh/setup-guide/sources/ebay.md
- docs/zh/setup-guide/sources/mysql.md
- docs/zh/setup-guide/sources/netsuite.md
- docs/zh/setup-guide/sources/shopify.md
- docs/zh/setup-guide/sources/walmart-marketplace.md
- docs/zh/setup-guide/sources/woocommerce.md
> CU-865bqm1p4_Airbyte_Roy--

- airbyte-integrations/connectors/source-ebay/source_ebay/source.py
> CU-865btmgq6_bugebay_Roy--

- airbyte-webapp/src/components/LoadingPage/LoadingPage.tsx
- airbyte-webapp/src/components/Table/Table.tsx
- airbyte-webapp/src/components/base/DropDown/DropDown.tsx
- airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/pages/ConnectionPage/ConnectionPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
All connection filteration and pagination bugs are resolved.
> CU-865btb6y4_BugWhen-no-matching-result-redirected-to-create-the-first-connection-page_Muhammad-Akif

- airbyte-webapp/src/App.tsx
Confirmation modal bug resolved properly.
> CU-860q24r40_Frontend-deployment-issue-debug_Muhammad-Akif

- airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
Visiting sources and destination pages result error bug resolved.
> CU-860q2g487_Clicking-on-destination-resulting-in-error_Muhammad-Akif

- airbyte-webapp/src/components/base/Input/Input.module.scss
- airbyte-webapp/src/components/base/Tooltip/Tooltip.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
- airbyte-webapp/src/scss/_colors.scss
> CU-8669fca66_Source-details-page_Anet-

- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/utils.tsx
- airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/locales/zh.json
In this PR I am done with the following:
1. Update statusLang based on backend
2. update connection page error resolved
> CU-860q24uw1_Update-statusLang-based-on-backend_Muhammad-Akif

- airbyte-webapp/build.gradle
fix the issue that airbyte can not show Chinese setup guide.
> CU-865bv1gbt_fix-the-issue-that-there-are-no-Chinese-guide-docs-in-localization_Jerry-Lee---

- airbyte-webapp/README.md
- airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
- airbyte-webapp/src/components/base/Input/Input.module.scss
- airbyte-webapp/src/components/base/Input/Input.tsx
- airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
- airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
- airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeCard.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
Supplementary modal styles and adjust some background colors.
> CU-865bv1zf0_Supplementary-modal-styles_Anet-

- airbyte-webapp/src/components/TabMenu/TabMenu.tsx
- airbyte-webapp/src/components/icons/NotificationIcon.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/index.tsx
some fix which need Akif and Anet in yuanrui-dev
> CU-3wm9kwh_FE-notification-settings_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/components/TabMenu/TabMenu.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
1. Fix the problem that the Tab component on the Source/Destination page is not selected.
2. Cancel left and right sliding fixed style
> CU-865bve682_Fix-the-problem-that-the-Tab-component-on-the-SourceDestination-page-is-not-selected_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/ConnectionStep/ConnectionStep.tsx
- airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/ImplementationTable.module.scss
- airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
- airbyte-webapp/src/components/Table/Table.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
> CU-865bvv4nz_BugConnectorLast-sync_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
- airbyte-webapp/src/components/EntityTable/components/AllConnectionsStatusCell.tsx
- airbyte-webapp/src/components/EntityTable/components/ConnectEntitiesCell.tsx
- airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx
- airbyte-webapp/src/locales/en.json
Connection page UI improvements
> CU-860q3x5uh_Connection-page-UI-improvements_Anet-

- airbyte-integrations/connectors/source-ebay/source_ebay/spec.yaml
- airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuth2Flow.java
- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/EbayOAuthFlow.java
> CU-860pzmhww_eBay-OAuth_Roy--

- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
- airbyte-webapp/src/services/users/UsersService.tsx
Delay in getting translated strings from backend has been resolved.
> CU-865bvygvz_bugModify-webapp-page-display-problem_Muhammad-Akif

- airbyte-webapp/src/core/Constants/statuses.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
Click to upgrade subscription, prompt status error
> CU-865bvv2a8_bugClick-to-upgrade-subscription-prompt-status-error_Muhammad-Akif

- airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
- airbyte-webapp/src/components/CreateConnectionContent/CreateConnectionContent.tsx
- airbyte-webapp/src/components/DataPanel/DefinitionCard.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/ExistingEntityForm.tsx
- airbyte-webapp/src/views/Connector/ServiceForm/FormRoot.tsx
- airbyte-webapp/src/views/Connector/TestConnection/components/TestingLoading.tsx
- airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
CU-860q3x5ze_Overall-size-improvements_Anet-
> CU-860q3x5ze_Overall-size-improvements_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Sign out change location and add confim popup.
> CU-860pu1eah_Sign-out-confirmation-message_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
UI related changes - add/edit source/destination page (Change the phrase to: Expand this form to continue setting up your integration )
> CU-860q5erk9_UI-related-changes---addedit-sourcedestination-page_Anet-

- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
> CU-865bwq9g8_bugsnowflake_Roy--

- airbyte-webapp/src/core/Constants/roles.ts
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
> CU-865bx7ga9_bugIn-the-Chinese-state-there-is-an-additional-authority-of-the-account-owner_Muhammad-Akif

- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
- airbyte-webapp/src/core/Constants/roles.ts
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
bug：In the Chinese state, there is an additional authority of the account owner
> CU-865bx7ga9_bugIn-the-Chinese-state-there-is-an-additional-authority-of-the-account-owner_Abi---

- airbyte-webapp/README.md
- airbyte-webapp/src/components/base/Button/Button.tsx
- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
UI related changes - change plan page(add back button)
> CU-860q5emvg_UI-related-changes---change-plan-page_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
UI related changes - config page UI(create_connection bgColor)
> CU-860q5xydr_UI-related-changes---config-page-UI_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/ConnectorBlocks/FormPageContent.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
- airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
1. Add a source page UI optimization
2. UI related changes - source/destination testing page
> CU-865bx1kun_Add-a-source-page-UI-optimization_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/ConnectionStep/ConnectionStep.tsx
- airbyte-webapp/src/components/base/index.tsx
- airbyte-webapp/src/components/icons/DashIcon.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/SelectDestinationPage.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTableBody.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
UI related changes - add new user
> CU-860q5ecq4_UI-related-changes---add-new-user_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
- airbyte-webapp/src/components/SingletonCard/SingletonCard.tsx
- airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
- airbyte-webapp/src/components/base/index.tsx
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
UI related changes - error message popup
> CU-8669pxbpw_UI-related-changes---error-message-popup_Anet-

- airbyte-webapp/.env
- airbyte-webapp/README.md
- airbyte-webapp/src/components/SimpleTableComponents/SimpleTableComponents.tsx
- airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
- airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
- airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.module.scss
- airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.tsx
- airbyte-webapp/src/views/Connection/CatalogTree/components/PathPopout.tsx
- airbyte-webapp/src/views/Connection/CatalogTree/styles.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.module.scss
- airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
UI related changes - stream table
> CU-860q5ff5h_UI-related-changes---stream-table_Anet-

- airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
> CU-860q8akf6_eBay-OAuth-redirect_Anet-

- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/EbayOAuthFlow.java
> CU-860q8akf6_eBay-OAuth-redirect_Roy--

- airbyte-webapp/README.md
- airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
- airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
- airbyte-webapp/src/components/base/DropDown/components/Text.tsx
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
- airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
- airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx
1. Indicate integration authentication status
2. Center the form in the Sign in page
> CU-860q8q04e_Indicate-integration-authentication-status_Anet-

- airbyte-webapp/.env
- airbyte-webapp/README.md
- airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
- airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
- airbyte-webapp/src/components/base/DropDown/components/Text.tsx
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
- airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
- airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx
Indicate integration authentication status
> CU-860q8q04e_Indicate-integration-authentication-status_Abi---

- airbyte-webapp/src/locales/zh.json
Save button text into Chinese translation updated. And 30% is not a bug @Roy has confirmed that we can test notification feature after creating new user through signup. We can't test it using old user.
> CU-865bzm9y0_bugAfter-clicking-Add-the-default-30-error-is-displayed_Muhammad-Akif

- airbyte-webapp/src/core/request/AirbyteRequestService.ts
- airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
- airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
- airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
- airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
- airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/components/LanguageDropdown.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
- airbyte-webapp/src/services/auth/AuthService.ts
Signin / Signup page language switch (done)
> CU-860q2g5w4_Sign-up--sign-in-page-language-switch_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
- airbyte-webapp/src/components/icons/CrossIcon.tsx
- airbyte-webapp/src/components/icons/TickIcon.tsx
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionPageTitle.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/SyncNowButton.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
> CU-860q8ckbw_Connection-config-update_Anet-

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-netsuite/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-netsuite/sample_files/config.json
- airbyte-integrations/connectors/source-netsuite/source_netsuite/source.py
- airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
- airbyte-integrations/connectors/source-netsuite/source_netsuite/streams.py
- docs/setup-guide/sources/netsuite.md
- docs/zh/setup-guide/sources/netsuite.md
1. `x.java`
2. `y.python`
</details>
</details> …
> Cu 860q8qcuf net suite sync issue carlos 

- airbyte-webapp/.eslintrc
- airbyte-webapp/README.md
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
UI when there is no source/destination
> CU-860q9u73q_UI-when-there-is-no-sourcedestination_Anet-

- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/NotificationFlag.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/SyncTable.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/UsageTable.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/UsageTableRow.tsx
> CU-865bztzh0_bugOn-the-setting-page-icons-and-texts-should-be-aligned-respectively_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/components/Pagination/Pagination.tsx
- airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
UI Too many paginations(connection page)
> CU-865bz04vx_Too-many-paginations_Anet-

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
- docs/setup-guide/sources/netsuite.md
- docs/zh/setup-guide/sources/netsuite.md
1. `x.java`
2. `y.python`
</details>
</details> …
> NetSuite 文档修改

- airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
UI issues with banner but with page scrolling otherwise its hard to manage
> CU-860q9v4ad_UI-issues-with-banner_Muhammad-Akif

- airbyte-webapp/src/core/domain/notificationSetting/notificationSettingService.tsx
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/services/notificationSetting/NotificationSettingService.tsx
- airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/components/IgnoreNotificationModal.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
I have just resolve this bug and push my latest code and generate a PR.
> CU-865c05nzg_bugWhen-I-click-to-close-the-prompt-it-still-shows_Muhammad-Akif

- airbyte-webapp/src/components/base/Button/BigButton.tsx
- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
- airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
user status management has been completed.
> CU-865c10u8z_bugAfter-choosing-to-unsubscribe-this-button-is-still-displayed-and-has-not-been-refreshed-in-time_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/SignOutIcon.tsx
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
> CU-860qbjnqd_Change-the-sign-out-icon_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/public/index.html
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
> CU-860qc62mb_Update-translation_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpdateStatusError.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
- airbyte-webapp/src/views/layout/Banners/BillingWarningBanner/BillingWarningBanner.tsx
> CU-865c1bz78_bug_Anet-

- airbyte-webapp/src/hooks/services/Health/HealthPollService.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
syncFail and syncSuccess notification shown
> CU-865c06dzy_bugCompleted-notification-not-shown-when-sync-succeeds-or-fails_Muhammad-Akif

- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/NotificationFlag.tsx
default flags are true now and update flag cursor issue is also resolved.
> CU-865c1kmc3_bugWhen-clicking-to-add-a-new-usage-limit-mail-and-app-notifications-should-be-turned-on-by-default_Muhammad-Akif

- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
> CU-866a057uj_Pricing-page-font-weight_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/core/domain/connector/SourceService.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/HeaderSection.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/HeaderSection.tsx
- airbyte-webapp/src/views/Connector/ConnectorCard/ConnectorCard.tsx
- airbyte-webapp/src/views/Connector/ConnectorCard/useTestConnector.tsx
- airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
- airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
1. Readjust the Source/Destination/Connection TestConnection component to remove scrolling
2. Copy Source/Destination flows add test endpoint(check_connection_for_update)
> CU-866a05878_Sourcedestinationconnection-test-page-UI_Anet-

- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
Resolve the user dropdown issue.
> CU-866a0pjt6_Bug-banner-shows-wrong-message_Muhammad-Akif

- airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/components/ConnectorCell.tsx
- airbyte-webapp/src/components/EntityTable/components/NameCell.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
Icon and name overlapping resolved
> CU-866a1ppxu_Icon-and-name-will-overlap-if-name-is-long_Muhammad-Akif

- airbyte-webapp/src/views/layout/MainView/MainView.tsx
> CU-865c46fn4_Fix-the-issue-on-airbyte-yuanrui-test-branch_Muhammad-Akif

- airbyte-webapp/README.md
- airbyte-webapp/src/components/base/DropDown/components/Menu.tsx
- airbyte-webapp/src/components/base/DropDown/components/Option.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Change the scrollbar to custom scroll instead of browser default
> CU-866a1pr5c_Change-the-scrollbar-to-custom-scroll-instead-of-browser-default_Anet-

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonAdsOAuthFlow.java
- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonSellerPartnerOAuthFlow.java
1. `x.java`
2. `y.python`
</details>
</details> …
> Amazon Ads/SP region & marketplace selection

- airbyte-webapp/README.md
- airbyte-webapp/src/components/ReleaseStageBadge/ReleaseStageBadge.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
Fixed react-intl compiling without HTML tag `<b>`
> CU-865c4qed1_The-b-tag-should-not-be-displayed-in-the-description_Anet-

- airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
git commit -m "CU-865c4t3aq - Click Back on the card number information filling page, the returned page is incorrect"
> CU-865c4t3aq_Click-Back-on-the-card-number-information-filling-page-the-returned-page-is-incorrect_Anet-

- airbyte-webapp/README.md
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
> CU-866a1pmwr_When-canceling-adding-new-user-the-input-field-will-show-as-required_Anet-

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
> CU-860qc3zyt_Update-Amazon-SP-fields_igor_

- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonSellerPartnerOAuthFlow.java
Fix the bug: the problem of getting an abnormal address in the SE region
> CU-860qdcfq4_Amazon-AdsSP-region--marketplace-selection_igor_

- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_specs.yaml
> CU-866a54b4v_Release-Plaid-as-a-source_Jerry-Lee---

- docs/setup-guide/sources/plaid.md
- docs/zh/setup-guide/sources/plaid.md
> CU-865ca5zzw_add-plaid-docs_Jerry-Lee---

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-shein/source_shein/source.py
- airbyte-integrations/connectors/source-shein/source_shein/spec.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> shein对接日期优化

- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonSellerPartnerOAuthFlow.java
In order to update Amazon seller partner regions, the 'spec' column in actor_definition table needs to be update. (databse :- airbyte-docker)
In the ticket comment section, I have already sent the database script
> CU-866abgqh6_Amazon-SP-region-update_Nick

- airbyte-webapp/src/core/domain/payment/Payment.ts
- airbyte-webapp/src/core/domain/payment/PaymentService.tsx
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/Health/HealthProvider.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/PaymentPage/FailedPaymentPage.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
- airbyte-webapp/src/pages/routePaths.tsx
- airbyte-webapp/src/pages/routes.tsx
- airbyte-webapp/src/services/payments/PaymentsService.tsx
- airbyte-webapp/src/views/layout/Banners/FailedPaymentBanner/FailedPaymentBanner.tsx
- airbyte-webapp/src/views/layout/Banners/FailedPaymentBanner/index.tsx
- airbyte-webapp/src/views/layout/Banners/index.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
send notification to user when payment fail
> CU-866aadcfv_FE-Send-notifications-to-user-when-payment-fails_Nick

- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
set replication_start_date to the previous day if it's not specified
> CU-865chxvj6_For-Amazon-Seller-Reports-default-to-the-previous-days-date-if-not-specified_Jerry-Lee---

- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/Health/HealthProvider.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/PaymentTable.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
- airbyte-webapp/src/services/notificationSetting/NotificationSettingService.tsx
add payment fail notification setting
> CU-865cjqx42_FE-consume-payment-failure-email-notification-endpoint_Nick

- airbyte-webapp/README.md
- airbyte-webapp/src/components/base/Button/BigButton.tsx
- airbyte-webapp/src/pages/PaymentPage/FailedPaymentPage.tsx
- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
2. Update payment on payment fail add loading indicator
> CU-865cknzdx_FE-update-payment-on-payment-fail-add-loading-indicator_Anet-

- airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
make netsuite object type filed required
> CU-866a17cnm_Make-Netsuite-object-type-field-mandatory_Ali-Ahmad

- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
QA: Netsuite object type field mandatory
> CU-865cmgewf_QA-Netsuite-object-type-field-mandatory_Abi---

- airbyte-webapp/src/core/AuthContext/AuthContext.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
- airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/VerifyEmailPage.tsx
- airbyte-webapp/src/services/auth/AuthService.ts
changes in sign-up flow and integrate resent email functionality
> CU-865cj6h6y_Multitenancy-11-sign-up-flow_Nick

- airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/products_report.py
change the start time of product stream report
> CU-865cqy9nt_improve-the-calculation-logic-about-the-default-pull-date-of-the-amazon-ads_Jerry-Lee---

- airbyte-webapp/README.md
- airbyte-webapp/src/components/DocumentationPanel/DocumentationPanel.tsx
- airbyte-webapp/src/core/request/apiOverride.ts
1. remove comment "// @ts-expect-error"
> CU-865czevdr_airbytedevtest_Anet-

- airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuth2Flow.java
> CU-865d285b4_change-airbyte-to-support-oauth2-callback-from-daspire-website_Jerry-Lee---

- airbyte-integrations/connectors/source-feishu/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-feishu/source_feishu/common.py
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/dashboard_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/field_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/member_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/record_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/role_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/table_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/view_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/source.py
- airbyte-integrations/connectors/source-feishu/source_feishu/spec.yaml
- airbyte-integrations/connectors/source-feishu/source_feishu/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> feishu bitable

- airbyte-integrations/connectors/source-feishu/Dockerfile
- airbyte-integrations/connectors/source-feishu/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-feishu/source_feishu/common.py
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/dashboard_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/field_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/member_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/record_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/role_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/table_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/schemas/view_list.json
- airbyte-integrations/connectors/source-feishu/source_feishu/source.py
- airbyte-integrations/connectors/source-feishu/source_feishu/spec.yaml
- airbyte-integrations/connectors/source-feishu/source_feishu/streams.py
- airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuth2Flow.java
Automatically login user in from daspire-website if user is already logged in
> CU-865d32e03_QA-Automatically-login-user-in-from-daspire-website-if-user-is-already-logged-in_haimin-

- airbyte-webapp/package.json
- airbyte-webapp/src/components/DocumentationPanel/DocumentationPanel.tsx
- airbyte-webapp/src/config/types.ts
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/core/request/apiOverride.ts
- airbyte-webapp/tsconfig.json
> CU-85ztzmema_BugCant-log-out_Shoaib-Ejaz

- airbyte-webapp/src/core/request/AirbyteClient1.ts
> CU-865ce7jtr_fix-the-issue-that-airbyte-webapp-can-not-build-successfully_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/src/config/frequencyConfig.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/formConfig.tsx
> CU-85zu0d75m_In-connection-config-when-manual-is-selected-it-shows-_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
> CU-85zu12rnk_bugAfter-failing-to-add-a-destination-click-Return-and-the-page-returned-is-incorrect_Shoaib-Ejaz

- airbyte-webapp/public/manifest.json
Changed to Daspire instead of Airbyte
> CU-85zu1bxnn_Remove-the-app-installation-popup-in-browser_Shoaib-Ejaz

- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
Issue fixed pagination implemented
> CU-85zu2fb9z_Check-the-issue-that-predaspirecom-doesnt-show-destinations-and-sources_Shoaib-Ejaz

- airbyte-webapp/src/components/Alert/Alert.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
Alert has added and message is showing
> CU-85zu0d6f2_Notify-the-user-free-trial-has-expired-when-they-try-to-save-a-connection_Shoaib-Ejaz

- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/formConfig.tsx
Issue fixed optimized the behaviour of switch
> CU-85zu0e0vv_It-takes-a-while-for-the-change-made-to-appear_Shoaib-Ejaz

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-walmart/Dockerfile
- airbyte-integrations/connectors/source-walmart/requirements.txt
- airbyte-integrations/connectors/source-walmart/source_walmart/source.py
- airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> Ability to connect to Walmart CA

- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-walmart/Dockerfile
- airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
> CU-85zu3udwz_BE-address-performance-issue-on-production_Nick

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DbConverter.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
create new api for source and destionation list with pagination
> CU-866atd7tv_BE-pagination-on-sourcedestination-pages_Nick

- airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
- airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
- airbyte-webapp/src/components/EntityTable/SourceTable.tsx
- airbyte-webapp/src/components/EntityTable/types.ts
- airbyte-webapp/src/core/domain/connector/SourceService.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/AuthPage/LoginNewPage/LoginNewPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
Remove unwanted requests from sources and destinations
> CU-866ayxydt_---DAPB20231013-011---performanceissueontheproductionenv_Shoaib-Ejaz

- airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
- airbyte-webapp/src/components/EntityTable/SourceTable.tsx
- airbyte-webapp/src/components/PageSize/PageSize.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
- airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
- airbyte-webapp/src/views/Connector/TestConnection/components/TestingLoading.tsx
- airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
UI improvements and now items per page is always showed
> CU-867917bp6_UI-improvements_Shoaib-Ejaz

- airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
- airbyte-webapp/src/components/JobItem/components/AttemptDetails.module.scss
- airbyte-webapp/src/components/JobItem/components/MainInfo.module.scss
- airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
- airbyte-webapp/src/components/SimpleTableComponents/SimpleTableComponents.tsx
- airbyte-webapp/src/components/base/Button/BigButton.tsx
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
- airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.module.scss
> CU-85zu4abdw_Webapp-responsiveness_Shoaib-Ejaz

- airbyte-webapp/src/components/Pagination/Pagination.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
Items per page location change
> CU-866b0a0zu_---DA20231029-069---UI-improvements_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/src/core/domain/connector/DestinationService.ts
- airbyte-webapp/src/core/domain/connector/SourceService.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
Pagination for SourceItem and Destination Item Page
> CU-866b0ezej_---DA20231101-070---Destination-setting-supports-the-pagination-of-connections_Shoaib-Ejaz

- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/formConfig.tsx
Issue fixed for creating connection
> CU-86792fj0e_bugSelect-manual-as-the-synchronization-method-and-the-error-will-be-500-when-connecting_Shoaib-Ejaz

- airbyte-webapp/src/components/PageSize/PageSize.tsx
- airbyte-webapp/src/components/base/Button/CustomButton.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/SelectDestinationPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/components/CreateControls.tsx
- airbyte-webapp/src/views/Connector/ServiceForm/components/CreateControls.tsx
> CU-866b0j4yp_---DA20231029-069---UI-improvements_Shoaib-Ejaz

- airbyte-webapp/src/core/jsonSchema/schemaToYup.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/EnabledControl.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/SyncNowButton.tsx
- airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx
Issue fixed and Reset Button UI Issue fixed
> CU-86792r4eq_BugMaximum-number-of-retries-for-deleting-report-generation-and-error-reporting_Shoaib-Ejaz

- airbyte-integrations/connectors/source-netsuite/requirements.txt
- airbyte-integrations/connectors/source-netsuite/source_netsuite/source.py
1. `x.java`
2. `y.python`
</details>
</details> …
> Fix Netsuite object type file issues

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DbConverter.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/converters/ApiPojoConverters.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
change connection page API response
> CU-866b0khcx_---DA20231101-071---Change-the-connection-page-api-to-improve-the-performance_Nick

- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/types.ts
- airbyte-webapp/src/components/icons/DisabledIcon.tsx
- airbyte-webapp/src/components/icons/FailedIcon.tsx
- airbyte-webapp/src/components/icons/GreenIcon.tsx
- airbyte-webapp/src/components/icons/GreenLoaderIcon.tsx
- airbyte-webapp/src/components/icons/WaitingIcon.tsx
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
Connection new api integrated and suggested changes are also changed
> CU-866b0r9tt_---DA20231012-066---Performance-issue-on-production---further-optimizations_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/src/components/DataPanel/components/Card.tsx
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/HeaderSection.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/HeaderSection.tsx
- airbyte-webapp/src/utils/imageUtils.tsx
- airbyte-webapp/src/views/Connector/ServiceForm/FormRoot.tsx
> CU-866b161nv_---DA20231112-077---change-the-icon-field-in-all-the-responses-to-string-_Shoaib-Ejaz

- airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java
- airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java
- airbyte-server/src/main/java/io/airbyte/server/converters/JobConverter.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
> CU-866b1vzq8_---DA20231122-089---improve-the-performance-of-getting-connection-s_Nick

- airbyte-api/src/main/openapi/config.yaml
- airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java
- airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
create new api /connections/status to get job status regarding connections ids
> CU-866b2050x_---DA20231122-089---improve-the-performance-of-getting-connection-s_Nick

- airbyte-webapp/.env
- airbyte-webapp/src/components/CreateConnectionContent/CreateConnectionContent.tsx
- airbyte-webapp/src/components/JobItem/JobItem.tsx
- airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
- airbyte-webapp/src/core/domain/connector/SourceService.ts
The breakdown of webapp issue fixed along with
the issue of sources.undefined text which is showing
> CU-866b1wk2e_---DA20231012-066---Performance-issue-on-production---add-connection-error_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
> CU-866b206j9_---DA20231122-089---improve-the-performance-of-getting-connections_Shoaib-Ejaz

- airbyte-integrations/connectors/source-shein/Dockerfile
- airbyte-integrations/connectors/source-shein/source_shein/source.py
1. `x.java`
2. `y.python`
</details>
</details> …
> shein 订单拉取日期优化

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
remove extra properties from destinations/connection/get  and sources/connection/get API
> CU-866b13zky_---DA20231012-066---Performance-issue-on-production---remove-extra-properties_Nick

- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-feishu/source_feishu/common.py
- airbyte-integrations/connectors/source-feishu/source_feishu/constraints.py
- airbyte-integrations/connectors/source-feishu/source_feishu/source.py
- airbyte-integrations/connectors/source-feishu/source_feishu/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> 集成飞书多维表获取子表数据

- airbyte-webapp/.env
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTable.tsx
Role tooltip issue fixed along with status api if connections are not avilable
> CU-866b238r2_---DAPB20231101-013---Nothing-happens-when-click-Upgrade-now-button-on-the-banner_Shoaib-Ejaz

- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
- airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
show banner according to user plan staus
> CU-866b25kha_---DA20231010-044---Billing-related-issues_Nick

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
- airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
- airbyte-webapp/src/utils/common.ts
- airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
add filter in source and destination page
> CU-866b13we1_---DA20231110-076---Filters-on-sources--destinations-page_Nick

- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
optmize source and destination list API
> CU-866b0r9nb_---DA20231012-066---Performance-issue-on-production---further-optimizations_Nick

- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/views/layout/MainView/MainView.tsx
Filters on Sources and Destination Page
> CU-866b13wd8_---DA20231110-076---Filters-on-sources--destinations-page_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/src/components/JobItem/JobItem.tsx
- airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
Connection Split api issue fixed page is shown first than status and along with that Error fixed in new-connection page which is showing oops page
> CU-866b2k9j8_---DA20231012-066---Performance-issue-on-production_Shoaib-Ejaz

- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
> CU-866b2u2tb_---DAPB20231207-017---Unable-to-select-a-particular-plan_Shoaib-Ejaz

- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java
> CU-866b2u24k_---DAPB20231207-015---Manual-schedule-not-display-correctly_Nick

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
- airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- docs/reference/api/generated-api-html/index.html
> CU-866b2wrg7_---DA20231110-076---Filters-on-sources--destinations-page_Nick

- airbyte-webapp/.env
- airbyte-webapp/src/components/DataPanel/DefinitionCard.tsx
- airbyte-webapp/src/components/NewMainPageWithScroll/NewMainPageWithScroll.module.scss
- airbyte-webapp/src/components/NewMainPageWithScroll/NewMainPageWithScroll.tsx
- airbyte-webapp/src/components/NewMainPageWithScroll/index.tsx
- airbyte-webapp/src/components/index.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
WebApp responsiveness on large,medium and small screen
> CU-860t4f19c_---DA20231011-064---Webapp-responsiveness_Shoaib-Ejaz

- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
change source and destination list to alphabetically order
> CU-860t4kzye_---DA20231010-047---Sourcesdestination-should-be-displayed-alphabetically_Nick

- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
Redirect to source page and destination page while adding source or destination
> CU-860t4zra3_---DA20231110-076---Add-sourcedestination-redirect_Shoaib-Ejaz

- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
Add source/destination redirect
> CU-860t4zra3_---DA20231110-076---Add-sourcedestination-redirect_Mary

- airbyte-webapp/src/core/jsonSchema/schemaToYup.ts
Netsuite Object Type highlited field issue fixed
> CU-860t4uyqq_---DAPB20231219-018---Netsuite-field-wrongly-highlighted_Shoaib-Ejaz

- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
- airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
- airbyte-webapp/src/views/Connector/TestConnection/components/FooterButtons.tsx
Back button remove from destination and source add page
> CU-860t55np2_---DAPB20231222-019---Remove-back-button-in-source-and-destination-testing-page_Shoaib-Ejaz

- airbyte-webapp/.env
- airbyte-webapp/package-lock.json
- airbyte-webapp/package.json
- airbyte-webapp/src/components/DatePicker/DatePicker.module.scss
- airbyte-webapp/src/components/DatePicker/DatePicker.test.tsx
- airbyte-webapp/src/components/DatePicker/DatePicker.tsx
- airbyte-webapp/src/components/DatePicker/index.tsx
- airbyte-webapp/src/components/NewButton/NewButton.module.scss
- airbyte-webapp/src/components/NewButton/NewButton.tsx
- airbyte-webapp/src/components/NewButton/index.tsx
- airbyte-webapp/src/components/NewButton/types.tsx
- airbyte-webapp/src/components/base/Input/Input.tsx
- airbyte-webapp/src/core/jsonSchema/schemaToUiWidget.ts
- airbyte-webapp/src/core/jsonSchema/schemaToYup.ts
- airbyte-webapp/src/hooks/services/Experiment/experiments.ts
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/scss/_z-indices.scss
- airbyte-webapp/src/setupTests.ts
- airbyte-webapp/src/views/Connector/ServiceForm/components/Property/Control.tsx
> CU-860t50mkv_---DA20231220-103---Integration-settings-optimization_Shoaib-Ejaz

- airbyte-api/src/main/openapi/config.yaml
- airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
- airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
> CU-860t4m566_---DA20231010-047---Abilitytosortconnectionssourcesdestinations_Nick

- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
- airbyte-webapp/src/components/EntityTable/SourceTable.tsx
- airbyte-webapp/src/components/EntityTable/components/SortButton.tsx
- airbyte-webapp/src/components/icons/ArrowDownIcon.tsx
- airbyte-webapp/src/components/icons/ArrowUpIcon.tsx
- airbyte-webapp/src/components/icons/SortDownIcon.tsx
- airbyte-webapp/src/components/icons/SortUpIcon.tsx
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
Sorting on connection,source,destination page
> CU-860t4mrfw_---DA20231010-047---Abilitytosortconnectionssourcesdestinations_Shoaib-Ejaz

- airbyte-webapp/src/components/Alert/Alert.tsx
- airbyte-webapp/src/components/EntityTable/hooks.tsx
- airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
- airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/locales/en.json
- airbyte-webapp/src/locales/zh.json
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionPageTitle.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/EnabledControl.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/TransformationView.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/DestinationConnectionTable.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/SourceConnectionTable.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
- airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
> CU-86encf8vw_---DA20231220-103---Configuration-save-function-changes_Shoaib-Ejaz

- airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
- airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
- airbyte-webapp/src/components/EntityTable/SourceTable.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
- airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Persist pagination and pageSize state after refresh
> CU-86endczz7_---DA20231010-047---Persist-paginationState-after-page-refresh_Shoaib-Ejaz

- airbyte-webapp/src/components/JobItem/JobItem.tsx
- airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
- airbyte-webapp/src/core/request/AirbyteClient.ts
Fixed Sync Status Showing Incorrectly
> Bug:Sync Status Show Incorrectly

- airbyte-webapp/src/core/domain/payment/PaymentService.tsx
- airbyte-webapp/src/core/request/DaspireClient.ts
- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
- airbyte-webapp/src/services/payments/PaymentsService.tsx
Fixed the api url of free-trial plan upgration first time
> Fixed the api url for free trial upgradation first time

- airbyte-webapp/src/core/domain/connector/DestinationService.ts
- airbyte-webapp/src/core/domain/connector/SourceService.ts
- airbyte-webapp/src/core/request/AirbyteClient.ts
- airbyte-webapp/src/hooks/services/useConnector.tsx
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/DestinationForm.tsx
- airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/SourceForm.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/components/DestinationForm.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
- airbyte-webapp/src/views/Connector/ConnectorCard/useTestConnector.tsx
- airbyte-webapp/src/views/Connector/ServiceForm/types.ts
- airbyte-webapp/src/views/Connector/ServiceForm/useBuildForm.tsx
Included worksapceId in apicalls
> Include workspaceid when making API calls

- airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/SelectPlanStep.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
Unsubscribed Plan (Upgrade Button Disabled Issue fixed)
> Unsubscribed Plan (Upgrade Plan Disabled Button Issue fixed)

- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
On Changeing Chinese Langugae Conccurent Job value Issue fixed
> On Changeing Chinese Languge Conccurent Job value Issue Fixed

- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
Add worksapce Id in sourc/update api
> Add worksapce Id 

- airbyte-webapp/src/core/request/AirbyteClient1.ts
- airbyte-webapp/src/hooks/services/useConnectionHook.tsx
- airbyte-webapp/src/hooks/services/useDestinationHook.tsx
- airbyte-webapp/src/hooks/services/useSourceHook.tsx
- airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/DestinationSettings.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/components/SourceForm.tsx
- airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/SourceSettings.tsx
- airbyte-webapp/src/views/Connector/ServiceForm/types.ts
Workspace Added in source/update api and destination/update api
> Worksapce Additon

- airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
> Shopify oAuth Issue

- airbyte-webapp/src/core/Constants/statuses.ts
- airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
Button disabled issue fixed in chinese lang
> Bug: Chinese language, update plan after unsubscribing, cannot choose original plan

- airbyte-webapp/.env
- airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Now New invited signup user details seen
> Webapp Invited User Issue Fixed

- airbyte-integrations/connectors/source-amazon-seller-partner/requirements.txt
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/ActiveListingsReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/CanceledListingsReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/InactiveListingsReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/OpenListingsReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/OpenListingsReportLite.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/OpenListingsReportLiter.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/ReferralFeeDiscountsReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/ReferralFeePreviewReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> Add data tables based on the prototype Amazon Seller Partner

- airbyte-integrations/connectors/source-amazon-seller-partner/setup.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> Cu 86epcu09w carlos 

- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/FBAFeePreviewReport.json
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> add FBA Fee Preview Report

- airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
made changes in ReportsAmazonSPStream class for replication_span_period
> source Amazon seller Partner

- airbyte-integrations/connectors/source-zoho-desk/Dockerfile
- airbyte-integrations/connectors/source-zoho-desk/setup.py
- airbyte-integrations/connectors/source-zoho-desk/source_zoho_desk/api.py
- airbyte-integrations/connectors/source-zoho-desk/source_zoho_desk/auth.py
made changes to  docker file and setup.py
> Add Source Zoho Desk

- airbyte-integrations/connectors/source-tiktok-marketing/source_tiktok_marketing/streams.py
- airbyte-integrations/connectors/source-tiktok-marketing/unit_tests/streams_test.py
- airbyte-integrations/connectors/source-tiktok-marketing/unit_tests/unit_test.py
> Add Source Tiktok Marketing

- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_specs.yaml
-add the spec information to airbyte-config for Hubstaff connector
> add the spec information to airbyte-config for Hubstaff connector

- airbyte-oauth/src/main/java/io/airbyte/oauth/flows/facebook/FacebookOAuthFlow.java
facebook marketing can fetch the account id list
> facebook marketing can fetch the account id list
